name: prime_video_flutter_ui_kit
description: "Prime Video Streaming App Flutter UI Kit"
publish_to: 'none'
# Flutter Version: 3.24.4
# Dart Version: 3.5.4
version: 1.0.4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  get: ^4.6.6
  share_plus: ^9.0.0
  file_picker: ^8.0.4
  pinput: ^5.0.0
  super_tooltip: ^2.0.7
  video_player: ^2.8.7
  chewie: ^1.8.1
  permission_handler: ^11.3.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/video/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/outfit/Outfit-Thin.ttf
          weight: 100
        - asset: fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: fonts/outfit/Outfit-Black.ttf
          weight: 900
